// This `postcss.config.js` file is automatically generated by `create-t3-app` as part
// of the Tailwind CSS setup. PostCSS is a powerful tool that transforms your CSS using
// JavaScript plugins.
//
// In a standard T3 application, its primary and essential job is to run the `tailwindcss`
// plugin. This plugin is what actually scans your files (as configured in tailwind.config.ts),
// finds the utility classes you've used, and generates the final, optimized CSS file that
// gets sent to the browser. This file is the bridge that connects Tailwind to the build process.
export default {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};
