// This `layout.tsx` file is the root layout for the Next.js App Router and is
// automatically generated by `create-t3-app`. It acts as the main UI shell that
// wraps every single page in the application. The `<html>` and `<body>` tags are
// defined here, ensuring a consistent structure for the entire site.
//
// The special `{children}` prop is where the content of the currently active
// page (e.g., `page.tsx`) will be rendered.
//
// Its most important role in a T3 app is to host global "Providers". Providers are
// wrapper components that give all child components access to a specific context
// or functionality. This file provides:
// - <Toaster>: For displaying global notifications.
// - <SessionProvider>: For making authentication data available to the app.
// - <TRPCReactProvider>: For enabling the type-safe tRPC client.

// This line imports the main global stylesheet for the entire application.
// In a Next.js/webpack environment, importing a CSS file like this tells the build process
// to include these styles in the final, bundled CSS file. Because this is the root layout,
// these styles will be available on every page. This file specifically contains the
// essential `@tailwind` directives that inject all of Tailwind's CSS into the app.
import "./globals.css";

// This imports the `Inter` font function from the `next/font` optimization package.
// This is Next.js's recommended way to handle web fonts. It improves performance and
// prevents layout shifts by downloading the font at build time and self-hosting it,
// rather than fetching it from Google Fonts on every page load.
import { Inter } from "next/font/google";

// This imports the `SessionProvider` React component. It is a "Context Provider" from NextAuth.js.
// Its job is to hold the user's authentication data (the "session"). When this component wraps
// a part of the application, it makes the session data available to any child Client Component
// that uses the `useSession` hook.
import { SessionProvider } from "next-auth/react";

// This imports the `SessionProvider` React component. It is a "Context Provider" from NextAuth.js.
// Its job is to hold the user's authentication data (the "session"). When this component wraps
// a part of the application, it makes the session data available to any child Client Component
// that uses the `useSession` hook.
import { auth } from "~/server/auth";

// This imports the main tRPC provider component for the frontend. This is another Context Provider,
// one that is specific to the T3 stack. It wraps the entire application to set up the type-safe
// tRPC client. Any component nested inside it can use the `api` object (e.g., `api.task.getAll.useQuery()`)
// to make API calls to the backend. It uses React Query behind the scenes to handle all data fetching logic.
import { TRPCReactProvider } from "~/trpc/react";

// This imports the `Toaster` component from the `react-hot-toast` library.
// This component does not render anything visible where it is placed in the code. Instead, it acts
// as a global container that listens for `toast()` function calls from anywhere in the app and
// displays the corresponding notification pop-ups at a designated position on the screen.
import { Toaster } from 'react-hot-toast';

// This calls the `Inter` font function that we imported from `next/font/google`.
// The returned `inter` object contains the necessary font data and a CSS class name.
// `{ subsets: ["latin"] }`: This is an optimization. It tells Next.js to only download the
// character subset needed for Latin-based languages (like English), reducing the font file size.
const inter = Inter({ subsets: ["latin"] });

// This calls the `Inter` font function that we imported from `next/font/google`.
// The returned `inter` object contains the necessary font data and a CSS class name.
// `{ subsets: ["latin"] }`: This is an optimization. It tells Next.js to only download the
// character subset needed for Latin-based languages (like English), reducing the font file size.
export const metadata = {

  // This sets the content for the `<title>` tag in the page's HTML head.
  title: "Full Stack Enhanced To-Do List",

    // This sets the content for the `<meta name="description" ...>` tag.
  description: "Built with T3 Stack",
};

// This defines the main React component for the root layout.
// `export default`: Makes this component the primary export of this file, which Next.js requires.
// `async`: This is critical. It declares that this is an "async component", which allows us to use
// the `await` keyword inside it. This is a feature of React Server Components.
// `function RootLayout(...)`: The name of our component.
// `({ children })`: This is object destructuring. The component receives a single `props` object,
// and this syntax immediately extracts the `children` property from it into a local variable.
export default async function RootLayout(

  // This is JavaScript object destructuring. It says "The first argument to this function
  // will be an object. From that object, I want to extract the `children` property
  // and make it available as a variable named `children`."
  {children,}

// This is TypeScript syntax defining the shape of the `props` object.
// It declares that the props object will have a `children` property,
// and the type of `children` is `React.ReactNode`, which can be any valid JSX content.
: {
  children: React.ReactNode;

// The function body is after this.
}) {

  // It calls the `auth()` function we imported from our server-side auth configuration.
  // The `await` keyword pauses the rendering of this component until the `auth()` function,
  // which checks for the user's session cookie and queries the database, has completed.
  // The resulting `session` object (or `null` if the user is not logged in) is stored in this constant.
  const session = await auth();

  // The `return` statement specifies the JSX that will be rendered as the page's HTML structure.
  return (

    // This renders the root `<html>` element for the entire page.
    // The `lang="en"` attribute is important for accessibility and SEO, declaring the page's language as English.
    <html lang="en">

      {
      // This renders the `<body>` element, which contains all the visible content of the page.
      // `className={inter.className}`: This line is the key to activating the optimized font from `next/font`.
      // The `inter` object we created earlier contains a pre-generated, unique CSS class name.
      // By applying this class to the `<body>`, we are telling the browser to use the self-hosted 'Inter' font
      // for all text within the body, as defined by our CSS variables in `globals.css`.
      // This system also automatically includes the necessary fallback fonts (`ui-sans-serif`, etc.), ensuring
      // that if 'Inter' fails to load for any reason, the text will still be readable in a standard system font.
      }
      <body className={inter.className}>

        
         {
        // This renders the `Toaster` component. It's self-closing as it doesn't wrap any children. */}
        // It invisibly sets up the global system for displaying toast notifications.
        // `position="top-center"`: This prop configures the Toaster to make all notifications appear at the top-center of the screen.
        }
        <Toaster position="top-center" /> 

        {
        // This renders the `SessionProvider` from NextAuth.js. It's a Context Provider that makes
        // session data available to all Client Components nested inside it.
        // `session={session}`: We are passing the `session` object (which we fetched securely on the
        // server with `await auth()`) as a prop to the provider. This is a critical optimization.
        //
        // If we did NOT fetch the session on the server, the `SessionProvider` would initially have no
        // data. When a Client Component calls `useSession()`, its `status` would first be `'loading'`
        // while it makes a client-side API call to fetch the session. During this time, we would
        // have to show a "Loading..." message to the user. When the data arrives, the UI would
        // "flash" as it re-renders to show the actual content.
        //
        // By passing the server-fetched session here, the `SessionProvider` is initialized with the data
        // from the very first render. The client-side `useSession()` hook will immediately have the data
        // and its `status` will be `'authenticated'` from the start, completely avoiding the flash.
        }
        <SessionProvider session={session}>

          {
          // This renders the tRPC provider, which is another Context Provider.
          // It sets up the client-side data fetching and caching layer for the entire application.
          }
          <TRPCReactProvider>

            {
            // This is the placeholder where Next.js will inject the actual page content
            // (e.g., the UI from `page.tsx` or `/tasks/page.tsx`). It is the "child" of all the providers.
            }
            {children}
          </TRPCReactProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
