// DELETE THIS FILE???



/* This file, `src/utils/api.ts`, is automatically generated by the `create-t3-app`
 * scaffolding tool. It has NOT been modified from its original, default state.
 *
 * Its sole and critical purpose is to be the central "entry point" for using your
 * type-safe tRPC API on the client side.
 *
 * The file performs two main actions:
 * 1. It imports the `AppRouter` type from your backend. This is the "blueprint" of your entire API.
 * 2. It uses this `AppRouter` blueprint to initialize the main tRPC client for React
 *    (using `createTRPCReact`) and exports it as a constant named `api`.
 *
 * By exporting this pre-configured `api` object, it provides a simple and consistent way
 * for all of your Client Components to import and use the tRPC hooks. For example, any
 * component can now `import { api } from "~/utils/api"` and immediately start making
 * type-safe API calls like `api.task.getAll.useQuery()`.
 */
import { createTRPCReact } from "@trpc/react-query";
import type { AppRouter } from "../server/api/root";

export const api = createTRPCReact<AppRouter>();